version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2
    steps:
      - checkout
      - run:
          name: Install hescore-hpxml
          command: |
            pip install .[dev] --progress-bar off
      - run:
          name: Run Unittests
          command: |
            python -m unittest discover -s tests
      - run:
          name: Run coverage tests
          when: always
          command: |
            set +e
            coverage run --source=hescorehpxml -m unittest discover -s tests > /dev/null 2>&1
            coverage report -m
            coverage html -d /tmp/coverage_report
      - store_artifacts:
          path: /tmp/coverage_report
          destination: coverage-report
      - run:
          name: Build documentation
          when: always
          command: |
            cd docs
            make html
            mkdir /tmp/docs
            cp -r _build/html/* /tmp/docs
      - store_artifacts:
          path: /tmp/docs
          destination: docs