version: 2
jobs:
  build-py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:  &install
          name: Install hescore-hpxml
          command: |
            pip install --user virtualenv
            python -m virtualenv env
            source env/bin/activate
            pip install --progress-bar off .[test]
      - run:  &unittests
          name: Run Unittests
          command: |
            source env/bin/activate
            pytest
      - run:  &stylechecks
          name: Run Style Checks
          command: |
            source env/bin/activate
            python -m flake8
  build-py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: *install
      - run: *unittests
      - run: *stylechecks
  build-py38:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: *install
      - run: *unittests
      - run: *stylechecks
      - run:
          name: Run coverage tests
          when: always
          command: |
            set +e
            source env/bin/activate
            python -m coverage run --source=hescorehpxml -m pytest > /dev/null 2>&1
            python -m coverage report -m
            python -m coverage html -d /tmp/coverage_report
      - store_artifacts:
          path: /tmp/coverage_report
          destination: coverage-report
      - run:
          name: Build documentation
          when: always
          command: |
            source env/bin/activate
            cd docs
            make html
            mkdir /tmp/docs
            cp -r build/html/* /tmp/docs
      - store_artifacts:
          path: /tmp/docs
          destination: docs

workflows:
  version: 2
  test_all_py_versions:
    jobs:
      - build-py36
      - build-py37
      - build-py38
